name: Build and Deploy to Anypoint Platform

on:
  push:
    branches:
    - dev
    - prod

env:
  ENV: ${{ vars.ENV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  variable-printer:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: secret-operator
      - name: Display structure of downloaded files
        run: ls -R
      - name: Run secrets-operator-script
        run: python secrets-operator-script.py --arg1 'mule-logger-sapi'
