
name: Build and Deploy to Anypoint Platform

on:
  push:
    branches:
    - dev
    - prod

jobs:
  variable-printer:
    runs-on: ubuntu-latest
    steps:
    - name: Print an Org variable
      run: echo "CONNECTEDAPPPASS value: ${{ secrets.CONNECTEDAPPPASS }}"
    - name: Print an Env variable
      run: echo "REGION value: ${{ secrets.REGION }}"
