name: Build and Deploy to Anypoint Platform

on:
  push:
    branches:
    - dev
    - prod

env:
  ENV: ${{ vars.ENV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  variable-printer:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        
      - name: Checkout common-settings repository
        uses: actions/checkout@v3
        with:
          repository: soumyajit-labs/common-settings
          path: common-settings
          token: ${{ secrets.HUB_REPO_TOKEN }}

      - name: Copy the secrets-operator-py file
        run: |
          mkdir -p tmp/artifacts
          cp common-settings/secrets-appender/secret-operator.py tmp/artifacts/
      
      - name: Use the downloaded file
        run: python tmp/artifacts/secret-operator.py --arg1 'mule-logger-sapi'
